### ISSUE TITLE
Fixing Abyss Section 

### ISSUE THREAD

**Issue by TiiaAurora** [TiiaAurora/LS-public-issue-tracker#1]
Make it so its easier trackable which char has done which Abyss Dungeon.

**Comment by xTavi** [comment]
This is definitely a good idea 💯 

I would suggest to move them at the weekly section for a character and adding each Abyss in descent order starting from the current tier.  For example if i am tier 2, i will be able to see only 3 abyssals from the sea and only 2 from the forge + all from tier 1. 

Also you can use the weekly abyss section as a summary for each character

**Comment by seangay** [comment]
The current roster checkboxes for abyssal are also not granular enough.

I believe the weekly limit is 6 clears per roster per dungeon.  

If the tracking of clears happens as suggested under the weekly section for the character you could determine how many have been done per abyssal and have that as an informational read-only display under the roster section.

**Comment by TiiaAurora** [comment]
The current plan is to have users track which abyssal dungeon they have done on which char without putting in a limiting factor. being more of a tracker and less a planner.

**Comment by TiiaAurora** [comment]
Changes are live
