### ISSUE TITLE
UI/UX Improvements and Suggestions

### ISSUE THREAD

**Issue by xTavi** [TiiaAurora/LS-public-issue-tracker#16]
Hi!

I hope my input will be helpful for the future of the application because I really like it and I want to help.

- The first problem you can identify is that having multiple chars will hide the daily aspect and you have to scroll up and down every time you do a daily on one of your alts. My suggestion is to move the daily piece on the right side ( instead of roaster tasks ), and keep weekly and roaster activities somewhere under. 

- Achieving this will lead to a better User Experience because because you will be using the daily tab around `nr_of_alts * daily_actities * number_of_subtasks //Una tasks have 3 subtasks` while the roaster activities are limited to `numer_of_roaster_activities`

- Another thing which can be related to my first point can be that the header is really big, it may be reduced by 25% without losing any information. Also, in the left side of the header you add a Server Time Clock and a Region Select Option which will change the time and the reset counter.

- Rename the Open button to Select because you don t open a character, you select it 😸 .

![image](https://user-images.githubusercontent.com/41364089/164225243-7efc279b-e7b7-4a35-951b-7abeea860c35.png)

- Try to have a wider padding for p2 sections ---> Improve readability
![image](https://user-images.githubusercontent.com/41364089/164234711-525fc616-a13a-4ddb-be75-8f04d4ee9f96.png) 

Old vs Suggestion

![image](https://user-images.githubusercontent.com/41364089/164234618-cec11916-7f6c-435c-aef9-6dc547707251.png)
Or you can go with an equal top-bottom padding.

Old 
![image](https://user-images.githubusercontent.com/41364089/164235085-e1861723-8da0-4360-86f5-a43b9cf5c82c.png)
Suggestion ( The dropdown near the class image is not centred in the suggestion, but I hope you understand the idea.  
![image](https://user-images.githubusercontent.com/41364089/164235421-2e7f4e66-de8c-427c-b488-54e555d2abfc.png)

- The last improvement suggestion I want to add is related to the way the days are displayed. I would like to have them ordered from Monday to Sunday and do not depend of the way the game is tracking days because of the 2 following reasons: 
1. The actual display is counter-intuitive for new users
2. 3months from now, if they will change the reset day due to an unknown cause we will have to update the UI too 🔁 

I hope this helps!

**Comment by TiiaAurora** [comment]
The time in the top shows the time remaining until the reset. It's not a clock. 
So far I thought they would all reset together and not at different times?

**Comment by xTavi** [comment]
I think we have to check this because probably on NA they have a different reset time. Or on EUC / EUW.

**Comment by TiiaAurora** [comment]
afaik the servers go all down together and patches are put out at the same time cause people have to be on the same steam version. 
We're discussing about the others ones at the moment :)
Main problem with changing sizes and even changing order is, that everything has to also be functional on every device. Since the majority of the users are on their smartphone every design choice that is made right now is "mobile first". But right now we see if there are ways we can find a compromise in this.

**Comment by xTavi** [comment]
I know mobile first is the way to go since I am a developer too, but on mobile version the sections are ordered ok. The first is the char selection, the daily tasks, daily roaster and then weekly. On the other side on the desktop version they are not 😿.

Also I really doubt that the majority of the users are on mobile, because the game is a desktop game, and many of them are using .xls for tracking, which is really hard to be completed on a mobile.

**Comment by TiiaAurora** [comment]
The next build will contain the following changes 

- changed the order the blocks are displayed
- changed header and footer size
- renamed the open button
- improved the padding of the boxes

Referring to our data, 2/3 of our users are on mobile so big design changes usually affect them the most. So responsiveness is one of our top priorities.
