### ISSUE TITLE
Expand summary section

### ISSUE THREAD

**Issue by TiiaAurora** [TiiaAurora/LS-public-issue-tracker#17]
Putting in more information like weeklies etc.

**Comment by NyuRailgun** [comment]
Any chance to get more details here? What exactly is the "summary section" and what purpose does it serve?

**Comment by coldino** [comment]
That would be the Overview block at the top. It shows the status of the core tasks of all characters at once. Also got new functionality today showing rest bonus, but we want to find a way to show more in it without it taking over.

**Comment by NyuRailgun** [comment]
> That would be the Overview block at the top. It shows the status of the core tasks of all characters at once. Also got new functionality today showing rest bonus, but we want to find a way to show more in it without it taking over.

Oh so it was such simple :D 
The new rest bonus tracking looks nice but as special for me as colorblind person it's hard to make a different between red and green such easily. Maybe working with blue / red combination or something like that (or give the option to activate accessibility options) could work out great for everyone.

**Comment by TiiaAurora** [comment]
> The new rest bonus tracking looks nice but as special for me as colorblind person it's hard to make a different between red and green such easily. Maybe working with blue / red combination or something like that (or give the option to activate accessibility options) could work out great for everyone.

We do not use colors to distinguish anything because of accessibility. You mean the contrast between the glows is not different enough?

**Comment by TiiaAurora** [comment]
Dedicated desktop view mode is now live.
