### ISSUE TITLE
Guild Task Tracker

### ISSUE THREAD

**Issue by mrloco110** [TiiaAurora/LS-public-issue-tracker#20]
As far as i know, the guild vendor is per character since the guilds are bound to them

**Comment by coldino** [comment]
Yup, they are, but they're also shared when you have multiple characters in a single guild.  We need to improve this - probably give each character a checkbox and let the user work it out for themselves.

**Comment by mrloco110** [comment]
that would be a great solution!

**Comment by mrloco110** [comment]
a button for guild tasks would be good too

**Comment by Teuferon** [comment]
Honest question @mrloco110 what is there to track about guild tasks? I mean... They are for the entire guild, you can but don't have to do them, or you can do them 10 times in a row and it doesn't matter.

**Comment by NyuRailgun** [comment]
> Honest question @mrloco110 what is there to track about guild tasks? I mean... They are for the entire guild, you can but don't have to do them, or you can do them 10 times in a row and it doesn't matter.

Do them once provides a huge amount of bloodstones a week, for a bigger guild that can include 1800 bloodstones.
It's not about tracking them for the guild , u tracking them for the character itself if ur character earned those one time per week bloodstone rewards from the weekly guild task tho 

I don't think it wouldn't be bad to make them trackable at least like the una task section right now:
![image](https://user-images.githubusercontent.com/52236837/167252279-3cb32601-f3b6-4ef5-a751-09b7416076d0.png)

**Comment by NyuRailgun** [comment]
> As far as i know, the guild vendor is per character since the guilds are bound to them

In general (idk if I missunderstand the creator) but the vendor
![image](https://user-images.githubusercontent.com/52236837/167252330-39a6ca2c-0a06-469b-9446-9d831f3f28d2.png)
is not weekly for the roster, it's a weekly character vendor even if more characters sharing the same guild. Every character have their own vendor. 




> Yup, they are, but they're also shared when you have multiple characters in a single guild. We need to improve this - probably give each character a checkbox and let the user work it out for themselves.

So this issue is (imo) not related to the question from the creator of this issue.

**Comment by TiiaAurora** [comment]
Guild tasks have been moved to the character section.
