### ISSUE TITLE
Option to 'Plan' Dailies

### ISSUE THREAD

**Issue by Keirsti** [TiiaAurora/LS-public-issue-tracker#22]
With a lot of alts, it can be a bit tedious to grind content every day, and there's a strong impetus to take advantage of the rest bonus systems in the game.

Adding the ability to 'plan' this rest bonus by, say, right-clicking on the node for a given day to 'flag' it in a visual way (like flagging a mine in Minesweeper) would be a great way to do this. Having the corresponding box in the Overview show up visually marked would then allow me to see, at a glance, what I had 'planned' to do in my rotation.

As a lazy visual example:

![image](https://user-images.githubusercontent.com/68172253/164699940-87e106a4-1d68-48e5-97c2-9a92cbef9836.png)

imo this is really just a nice to have as there are other methods - I just order my alts on my char select screen and rotate through pairings of the ones at T1+ - but it could be helpful. :)

**Comment by coldino** [comment]
We plan to add a way to track and show rest bonus, so this should cover your needs I hope.

I'll close this issue and use #3 to track that.
