### ISSUE TITLE
Current day of the week is showing incorrectly.

### ISSUE THREAD

**Issue by seangay** [TiiaAurora/LS-public-issue-tracker#23]
I am located in Melbourne Australia and the current day is being recognised as a day in front of what it actually is.  

Today is Saturday for me and the site is having Sunday as being the active day... it isn't a large deal, but it does throw off the options for selection under "Roster Tasks > World".. 

for example as the day on the site is being incorrectly identified as Sunday the world bosses are not selectable even though I have done them today.

**Comment by TiiaAurora** [comment]
On which server are you playing? Cause NA and EU do not have world bosses today.

**Comment by seangay** [comment]
Sorry, only just saw this message.  I play on Shandi. 

I think my point is valid regardless of when you look at what is active.  Servers reset for me in Melbourne at 8pm...

To give you a concrete example, last night when I was playing the active day on the site was showing as Wed when it is actually my Tues evening.  It stays that way until 12am when my day syncs up with the site. 

Hopefully that makes sense?

**Comment by coldino** [comment]
Ah yes. Thanks for the extra information.

This is kind of the opposite of a request we originally had from a different user. It is currently aligned to the "reset day", showing the name of the day with the majority of the hours in your timezone.

What you should see is the next column highlighted at reset time, and the column headers never changing. We thought this was important to maintain consistency across the globe. You just have to think of it as "reset day" and not quite "your day".

**Comment by seangay** [comment]
That's ok. I can see the perspective and honestly I don't know how you would "fix" it TBH..

It's just my brain I need to fight with a little when I am clicking completion stuff.  Thanks for spending the time looking over this issue.. ill close this one out now.
