### ISSUE TITLE
Resting bonus tracking [Suggestion]

### ISSUE THREAD

**Issue by xsFluffy** [TiiaAurora/LS-public-issue-tracker#25]
Perhaps a section or option to enable resting bonus tracking. It'd be nice for me to keep track of how much bonus my alts have. I'll know which character and what type of daily I should do first. It could also prevent stacking up too much resting bonus.

It could keep track and calculate the added/substracted rest bonus based on the tracking information we currently give. 

There are no label options for me, so I've added [suggestion] in the title.

**Comment by TiiaAurora** [comment]
Hey, it's the feature we work on at the moment. See #3
