### ISSUE TITLE
Guardian Event Extended to May 19

### ISSUE THREAD

**Issue by TC-Timecop** [TiiaAurora/LS-public-issue-tracker#27]
Please allow us to track again and update the event schedule in the event slider display

**Comment by coldino** [comment]
We updated the end date for this event yesterday, so it should still be trackable.

What might have confused things is we messed up the "ends in ..." display for events so it was showing it ended on Thursday, even though it ends on a totally different Thursday! This is now also fixed and will be released later today.

Let us know if there's still an issue after the update.

**Comment by coldino** [comment]
This is live now.
