### ISSUE TITLE
Rest bonuses not tracked properly

### ISSUE THREAD

**Issue by evilandrex** [TiiaAurora/LS-public-issue-tracker#29]
It appears that the Rest bonuses across the board has bugs and doesn't match in-game behavior. 

- It appears that rest bonuses reset on weekly reset. Intended behavior: rest bonuses are not reset weekly. 
- It appears that if you had 10 rest bonus from the previous day, when you do a chaos dungeon, it'll spend the entire 30 (it should result in just going back to 10). Intended behavior: rest bonuses are only spent when there is enough to gain a bonus (e.g., if you had only 10 rest point for chaos dungeon, doing a chaos dungeon will not decrement this).
- If you use the minus button to override rest bonus calculation when it is already at 0, you get a NaN (and if you save it, it breaks the UI until reload). Intended behavior: minusing from 0 should either be disabled or just leave the value at 0.

The rest bonuses currently is also not very intuitive in how it reflects what you should get when you do a click a checkbox. Essentially, the rest bonuses calculation increment automatically every day assuming you don't do today's daily and then decrement if you do do today's daily. But this isn't how rest bonuses increment in-game. Today's rest bonus status should start (if no boxes are checked) based on the previous day's state, then change (if needed) based on checkboxes. Of course override can still act in the same way as it does now.

Thank you for the useful tool. I appreciate the continued development.

**Comment by coldino** [comment]
Could you check the latest version of the tool? We revamped the rest bonus system as it was confusing too many people.

**Comment by evilandrex** [comment]
![image](https://user-images.githubusercontent.com/31050518/165858432-55ebc1c7-7ce8-4636-8b8f-01c89e619318.png)
This still isn't quite right. For Chaos Dungeon, starting at 10 rest bonus (which is half of a full bar in-game), completing both chaos dungeons for the day should make it such that the day ends with 10 rest bonus (and the next day also to start with 10 rest bonus).

The other issues appear to be rectified.

**Comment by TiiaAurora** [comment]
NOW I got it. Sorry for being slow today :D 
The fix is in the build for the next patch :)

**Comment by coldino** [comment]
Whoops! Fix is live now. Thanks for the details.
