### ISSUE TITLE
how to download as an app?

### ISSUE THREAD

**Issue by mrloco110** [TiiaAurora/LS-public-issue-tracker#30]

**Comment by TiiaAurora** [comment]
On Android when you open the site in a browser you should see a little info window at the bottom asking you if you want to install the page as an app. Just confirm it. 
On your PC in Chrome you have an additinal icon in your address bar. 
Firefox will need an extension for it. (look for "installing pwa with firefox")
Edge also has an icon in the address bar.

**Comment by mrloco110** [comment]
> On Android when you open the site in a browser you should see a little info window at the bottom asking you if you want to install the page as an app. Just confirm it. On your PC in Chrome you have an additinal icon in your address bar. Firefox will need an extension for it. (look for "installing pwa with firefox") Edge also has an icon in the address bar.

when an update occurs, it will be auto updated too?

**Comment by TiiaAurora** [comment]
Updates will be downloaded in the background and will be applied as soon as you reopen Leapstone.

**Comment by Teuferon** [comment]
I am just gonna add that you can download it on iOS by opening the site in Safari, clicking the native iOS share button, scrolling down, and clicking "Add to Home Screen". You will get your PWA on the home screen and can run as a kind of a "native" app.

**Comment by coldino** [comment]
Thanks for the extra info, good to know.

I think we can close this now.
