### ISSUE TITLE
Make the current Day to the first / last Column

### ISSUE THREAD

**Issue by MasterOfBytes** [TiiaAurora/LS-public-issue-tracker#33]
It would be great if the Column-Order of the "ToDos" would be dynamic, so that it will always start with the current day in the first column. The green marker of the current day is great, but i think this way it would be a little bit easier / better to find.
( Or the last Column )

**Comment by coldino** [comment]
Thanks for the suggestion. However, this would make it impossible to adjust ticks from the previous day - something I often do when I forgot to update the app.

Having discussed this, we think the current approach is the one we'll stick with.
