### ISSUE TITLE
Auto check lower tier phases in the weekly abyssal section

### ISSUE THREAD

**Issue by artofsound** [TiiaAurora/LS-public-issue-tracker#36]
On the weekly abyssal section, if you click for example Argos 1385, make it so 1370 is auto checked etc.

https://user-images.githubusercontent.com/39335345/166677066-359d171e-ea12-4515-bcc7-ae825ca31395.mp4

**Comment by TiiaAurora** [comment]
We may have overlocked this one when we added the autofilling option. Will put it into the next patch. Thanks for the hint!

**Comment by coldino** [comment]
Done!
