### ISSUE TITLE
Show rest bonuses on the overview section

### ISSUE THREAD

**Issue by artofsound** [TiiaAurora/LS-public-issue-tracker#37]
Actually I'm eagerly waiting for this feature ingame, but in the meantime, it would be nice to have it already.
If you want to do a 3 day rotation, it would be really helpful to see, if some character has enough rest bonus up, especially if you skip one day of the 3 day rotation.

Maybe you can add it into the existing elements to have less cluttering.

![grafik](https://user-images.githubusercontent.com/39335345/166678758-da1b3c70-7490-4d58-8954-5b47bf6082f5.png)

Maybe like this, have a dark green circle if rest bonus for that dungeon/raid is obtainable.

![grafik](https://user-images.githubusercontent.com/39335345/166679160-507d74ab-b000-4410-94f1-40e049cbdfdc.png)

**Comment by artofsound** [comment]
Another suggestion, maybe just in a darker color.

![grafik](https://user-images.githubusercontent.com/39335345/166683531-701bc03b-26c1-4781-b61f-3f983613421f.png)

**Comment by artofsound** [comment]
I don't really mind how it is displayed, at least in less hidden/nested manner like it is right now.

Additionally, how it looks in KR.
![https://i.imgur.com/pFZuFvu.png](https://i.imgur.com/pFZuFvu.png)

**Comment by coldino** [comment]
This is now live.

* A pale white glow shows enough rest for a full day's activities.
* A red glow means it hit 100 and rest will be lost if you don't act.

Unsure how best to show/explain these colours in the UI. Anyone have ideas?

**Comment by LittleBigDev** [comment]
Thank you, great news!
