### ISSUE TITLE
Cross Week Rest Bonus Tracking

### ISSUE THREAD

**Issue by NyuRailgun** [TiiaAurora/LS-public-issue-tracker#38]
After a weekly reset the whole track of the rest bonus gets lost. Not every characters starts with 0 rest bonus at reset day.
As special if you play characters with rest bonus across two weeks you lose the "original rest bonus number" from the previous week and totally lose track of the current rest bonus of the characters after a week reset. 
Possible solution:
Make a field to transfer the last days "rest after" and base the new week at this value.
![Bild_2022-05-05_125959201](https://user-images.githubusercontent.com/52236837/166910185-c4276651-8d66-4507-82e3-66fd331dc6fd.png)

**Comment by coldino** [comment]
Interesting. We tested this during development and I've just this second done it with my own live data - it carried over without issue.

On the other hand @TiiaAurora also just tested it and it did not carry over, so we have an issue to investigate.

Thanks for the report. Will look into it.

**Comment by NyuRailgun** [comment]
Is there anything I can provide to locate the issue?

**Comment by coldino** [comment]
If you happened to do an export of your data yesterday or just before the reset, that would be a useful data point.

**Comment by NyuRailgun** [comment]
> If you happened to do an export of your data yesterday or just before the reset, that would be a useful data point.

Sadly I have no export for this time stamp tho 




> Also, we found a potential issue where if you didn't view a particular character at all it wouldn't have its rest bonus calculated, and therefore couldn't be carried over. Could this have applied in your case?

I can't remember if I clicked a character before pressing the weekly reset. 
But in general I can provide my data for research since I found something interesting.
Export time: After reset at 3.10 pm gmt+1

---
I did the export and reviewed the json. I found something interesting at the week data:
![Bild_2022-05-05_151716966](https://user-images.githubusercontent.com/52236837/166931111-7aad55d2-4086-4cfc-beef-61010b0e551e.png)
![Bild_2022-05-05_151848258](https://user-images.githubusercontent.com/52236837/166931344-e6164fca-9ff8-446c-bd0e-12532803c596.png)
[leapstone-data.zip](https://github.com/TiiaAurora/LS-public-issue-tracker/files/8631527/leapstone-data.zip)

**Comment by coldino** [comment]
I'm going to have to assume the rest JSON you found was for a different character than your screenshot as I can't see a way that can happen.

We've just released a revamped version of the rest system. On the assumption that it was unviewed/uncalculated values that didn't carry over, this should fix it as everything is calculated and cached on load, which also lets us display it in the Overview.

If anyone sees this again, please open a new issue.
