### ISSUE TITLE
Responsive Custom Note (QOL)

### ISSUE THREAD

**Issue by NyuRailgun** [TiiaAurora/LS-public-issue-tracker#39]
Please make the Custom Note section responsive to the containing notes.
If you extend the preset (2 row window) you have to resize the window manually every time you reload the page.
![image](https://user-images.githubusercontent.com/52236837/167159870-8ee98e1c-a80f-425b-85cf-3e04454afecc.png)
![image](https://user-images.githubusercontent.com/52236837/167159915-0845bef8-69ee-428f-b450-0efb664aabeb.png)

**Comment by TiiaAurora** [comment]
Thanks for the feedback. We will put this on or list for improvements.

**Comment by coldino** [comment]
You should find this is improved now. Memos open up big enough to fit their content, up to a maximum of about 15 lines.
