### ISSUE TITLE
Reinstate the ability to resize the custom note sections.

### ISSUE THREAD

**Issue by seangay** [TiiaAurora/LS-public-issue-tracker#45]
It used to be possible to resize the custom notes.  It seems that the following CSS selector has been added... if you disable it via dev tools I can get it back, but I have to remember to do that each time I refresh.. 

```javascript
textarea.svelte-1xh998w {
    min-height: -webkit-min-content;
    min-height: -moz-min-content;
    min-height: min-content;
    width: 100%;
    /* resize: none; */
    padding: 0.25rem 0.75rem;
    line-height: 1.375;
}
```

**Comment by TiiaAurora** [comment]
Unfortunately that clashes with #39 asking for making the note size responsive to the content. 
May I ask what's your usecase?
