### ISSUE TITLE
Expanding layout to prevent having to changes tabs for dailies and weeklies

### ISSUE THREAD

**Issue by Zetsuban** [TiiaAurora/LS-public-issue-tracker#46]
There's a hella lot of space on both sides, what would be great would be using that space to prevent having to change tabs while doing dailies since it is kind of a pain. It's unnecessary clicking.
![Inkedchrome_XgouGfHOhi_LI](https://user-images.githubusercontent.com/22130612/168919983-9b52610e-4262-479e-939e-7a0139a37f50.jpg)
![chrome_XgouGfHOhi](https://user-images.githubusercontent.com/22130612/168920006-cd3f8d2d-dac5-4dd3-ba74-77be3c968892.png)

Not the best paint design but you get the idea, it would prevent having to change tabs for dailies/ weeklies and allow for a more global view of your weekly progress.

**Comment by TiiaAurora** [comment]
Right now we are working on a dedicated desktop-view. 
The main page is created with the idea of mobile first, so it looks good and works perfectly on the phone but also works on the desktop pc with the same functionalities. 
The fullpage view will need a little bit of time still but it should fullfil all your needs for using the app :)

**Comment by TiiaAurora** [comment]
The dedicated desktop view is now live
