### ISSUE TITLE
QOL suggestions

### ISSUE THREAD

**Issue by xsFluffy** [TiiaAurora/LS-public-issue-tracker#47]
https://prnt.sc/lalaXhsnmWpZ
- An option to mark dailies in this (image in URL) menu by clicking on the dots.

- 3 guild weeklies

- Guild requests

**Comment by coldino** [comment]
Hopefully the new matrix view takes care of the first request. Supporting 3 guild weeklies is on our todo list.

Guild requests... what's this?

**Comment by TiiaAurora** [comment]
Closed
