### ISSUE TITLE
Delete button not working all the time

### ISSUE THREAD

**Issue by tzuku** [TiiaAurora/LS-public-issue-tracker#48]
Tried to delete a character i no longer wished to track - felt like i had to press it in a very specific spot for the confirmation pop up to appear, either that or it just works very rarely for some reason

**Comment by coldino** [comment]
Whoops, this is to do with how defocussing the name edit box hides the delete button. I'll have a fix out later.

**Comment by TiiaAurora** [comment]
Fixed in the latest patch
