### ISSUE TITLE
Grey out when chaos portal and/or fieldbosses/ships are not available

### ISSUE THREAD

**Issue by TiiaAurora** [TiiaAurora/LS-public-issue-tracker#5]
not every even can be done every day.

**Comment by TiiaAurora** [comment]
Thu: Chaos Gate, Adv Island, Ghost Ship, Co-op Sailing
Fri: Field Boss, Adv Island, Co-op Sailing
Sat: Chaos Gate, Adv Island, Ghost Ship, Co-op Sailing
Sun: Chaos Gate, Field Boss, Adv Island, Co-op Sailing
Mon: Chaos Gate, Adv Island, Co-op Sailing
Tue: Field Boss, Adv Island, Ghost Ship, Co-op Sailing
Wed: Adv Island, Co-op Sailing

**Comment by coldino** [comment]
Done.
