### ISSUE TITLE
Highlight daily bubbles with full rest bonus in matrix view

### ISSUE THREAD

**Issue by Hadares** [TiiaAurora/LS-public-issue-tracker#50]
I love the new matrix view, and I would stay in it all the time, but I have to switch back to the original view to quickly see which characters have full bonus for a given day via highlighting like below:
![image](https://user-images.githubusercontent.com/106554201/171046344-71dda3f0-26f0-4c0e-a1fa-14d59bf3e0f3.png)

Here's the same character with the same bonuses in the matrix view:
![image](https://user-images.githubusercontent.com/106554201/171046472-d881e06a-81ff-41e9-bfa5-a84c34e843fc.png)

**Comment by TiiaAurora** [comment]
The rest-bonus will be added with the next patch. We had been working on it already. :)

**Comment by Hadares** [comment]
Awesome, glad to hear it! Thanks so much, your site is great.
