### ISSUE TITLE
bug on main tab

### ISSUE THREAD

**Issue by mrloco110** [TiiaAurora/LS-public-issue-tracker#53]
![image](https://user-images.githubusercontent.com/26129311/189029870-100ed237-37d4-4f61-a1d5-e5b5e25d140e.png)

**Comment by coldino** [comment]
Could you let us know if this is still an issue? Maybe the host had an issue, but it seems to be working today.

**Comment by mrloco110** [comment]
> Could you let us know if this is still an issue? Maybe the host had an issue, but it seems to be working today.

still bugged

**Comment by TiiaAurora** [comment]
What happens if you open the page in an incognito tab? Maybe some extension is blocking the Javascript? I couldnt replicate the error here.

**Comment by mrloco110** [comment]
> What happens if you open the page in an incognito tab? Maybe some extension is blocking the Javascript? I couldnt replicate the error here.

that way it works, i tried to disable all addons, but does not work w/o incognito

**Comment by coldino** [comment]
Okay, was going to suggest you might need to clear your browser cache, as it seemed to have an old copy of the main page.

Thanks for the update. Closing.
