### ISSUE TITLE
Machinist is in the wrong class category

### ISSUE THREAD

**Issue by ghosttechx** [TiiaAurora/LS-public-issue-tracker#55]
Machinist should be on the Gunner side not Assassin
![image](https://user-images.githubusercontent.com/32527697/193158384-ad176cd4-9a09-4727-bbdd-242bfbe87d2c.png)

**Comment by TiiaAurora** [comment]
Thanks! We will change that today

**Comment by TiiaAurora** [comment]
Is fixed in the newest patch :)
