### ISSUE TITLE
Glaivier not recognized as a class when choosing engravings.

### ISSUE THREAD

**Issue by shyce** [TiiaAurora/LS-public-issue-tracker#56]
Attached some images. I can still set engravings and everything works. Just a big yellow banner saying I need to choose a class first. Not doing this with my other characters. Actually I just checked - also doing it on my Arcanist. 

![image](https://user-images.githubusercontent.com/30611382/198853151-33e869e5-4f7f-49a9-85c6-4e626565d5bf.png)
![image](https://user-images.githubusercontent.com/30611382/198853160-938f26a6-db2b-4761-b580-99cb679eca13.png)
![image](https://user-images.githubusercontent.com/30611382/198853196-819d4e4e-18dd-404a-b6e7-922e514eee82.png)

**Comment by shyce** [comment]
There is also no Pinnacle skill in the engravings list. =) Probably missing arcanist skill too I'm guessing

![image](https://user-images.githubusercontent.com/30611382/198853216-56bd4684-404e-4a38-bcfb-93f422057115.png)

**Comment by shyce** [comment]
Same with Empress's Grace

![image](https://user-images.githubusercontent.com/30611382/198855422-030fda3b-5f71-4904-9e57-a4597fe0a562.png)

**Comment by coldino** [comment]
Yikes, this is something we missed on the classes that have been added after release 😟 

We'll get this fixed asap.

**Comment by TiiaAurora** [comment]
fixed in the next update.
