### ISSUE TITLE
Open source the project

### ISSUE THREAD

**Issue by nwk6661** [TiiaAurora/LS-public-issue-tracker#60]
Hey,

Definitely appreciate all the work you have done on Leapstone, myself and a couple other guildies use it as our main tracker. I've noticed there's a decent amount of issues opened for QoL requests, along with some other changes I myself would like to make.
By open sourcing the project you would allow the community to contribute the changes themselves if you guys do not have the time to implement these small changes. Although you make changes quickly in regards to new content, there are some features people have been hoping for for a while.

I understand the pros (and cons) of keeping software closed source, but I'm asking you to at least consider open sourcing the project. You would still have full control in that you can accept or deny any pull requests you receive for whatever reasons, but it would allow rapid expansion of Leapstone to make it best it can be for everyone.

Thanks!

**Comment by nwk6661** [comment]
Could I get an update on this?

**Comment by TiiaAurora** [comment]
We talked internally to not open source the project yet.
