### ISSUE TITLE
"Challenge Abyssals" field should only have two check boxes.

### ISSUE THREAD

**Issue by Travanoid** [TiiaAurora/LS-public-issue-tracker#63]
I don't think there's any set of challenge abyssal dungeons with three wings, so one of these checkboxes should be removed.
![image](https://user-images.githubusercontent.com/28797307/232174410-ed49718d-a4d8-4a65-95b0-612127aaeea7.png)

**Comment by TiiaAurora** [comment]
Removed the third checkbox from Challenge Abyssals.
