### ISSUE TITLE
Add Kayangel 

### ISSUE THREAD

**Issue by nwk6661** [TiiaAurora/LS-public-issue-tracker#64]
Eternal Cradle of Light abyss dungeon, 4 gates

**Comment by netzkopf** [comment]
3 Gates by now

**Comment by coldino** [comment]
Yikes I'm sorry I totally forgot that this still needed doing. I haven't played the game in some time, so can I get some confirmation? It looks like this is a strange mix of Abyssal Dungeon, but acting more like a Legion Raid. Can it just be treated like this?

![image](https://github.com/TiiaAurora/LS-public-issue-tracker/assets/28345893/e4c9eb50-4030-4500-b2af-d80ba1322764)

**Comment by netzkopf** [comment]
Well, it is a raid with less mechanics as the legion raids and it does show up under "abyssal dungeons", so I think it's perfectly right like this, thank you.

While you're at it, can you also adjust the other recent changes with the gates?
Vykas has only 2 gates now (3 before) and Brelshaza has 4 instead of 6 gates now.
And there is an additional legion raid called "Akkan" with 3 gates.

**Comment by rodrigokiller** [comment]
Yes. Also, there is a new "reset time" every 15 days. Tomorrow this time will be resetted. The Brelshaza Gate 4 is only possible to do every 15 days. That means that if I haven't done Brel Gate 4, I can do it today. Tomorrow it will be reset and I can do it again, but next week (10/18) I will not be able to do Brelshaza G4 again. 
Brelshaza G1 -> Old Brelshaza G1
Brelshaza G2 -> Old Brelshaza G3
Brelshaza G3 -> Old Brelshaza G4
Brelshaza G4 -> Old Brelshaza G6

**Comment by coldino** [comment]
Excellent, thanks for the additional details. These changes should now be live.

Can't immediately think of a good way to support the two-week Brelshaza reset so I've simply highlighted gate 4 to remind that it is special. Might re-visit at some point.

As neither of us no longer regularly play the game we'll be relying on reports like this for updates in future. Don't expect significant new functionality, but we'd like to keep it up-to-date with the game if possible.
